src/bin/generate.ts
src/chapters/02-building-pages.md
src/chapters/03-automated-testing.md
src/chapters/04-component-basics.md
src/lib/index.ts
src/lib/plugins/todo-links/index.ts
src/lib/plugins/todo-links/walker.ts
src/lib/plugins/zoey-says/walker.ts

This requires using the `[some text][TODO: some comment]` syntax instead, because the `[some text](TODO: some comment)` syntax parsed into a `LinkReference` (`[some text]`) plus a regular `Text` node (`"(TODO: some comment)"`) as siblings.

Remove TODO links from the output

---

.travis.yml

I'm not sure if `-o5` is the right tradeoff. If it's too slow I think we can probably dial it down without much impact on the compression result.

Optimize screenshots

---

.travis.yml
scripts/deploy.sh
scripts/optimize-screenshot.sh
src/bin/generate.ts
src/chapters/01-orientation.md
src/chapters/03-automated-testing.md
src/chapters/04-component-basics.md
src/lib/plugins/run-code-blocks/cfg.ts
src/lib/plugins/run-code-blocks/commands.ts
src/lib/plugins/run-code-blocks/directives/command.ts
src/lib/plugins/run-code-blocks/directives/file/patch.ts
src/lib/plugins/run-code-blocks/directives/server/start.ts
src/lib/plugins/run-code-blocks/directives/server/stop.ts
src/lib/plugins/run-code-blocks/index.ts
src/lib/plugins/run-code-blocks/lineno.ts
src/lib/plugins/run-code-blocks/options.ts
src/lib/plugins/run-code-blocks/parse-args.ts
src/lib/plugins/run-code-blocks/parse-error.ts

Attempt to ensure the markdown and screenshots doesn't produce slightly different results on each build.
Currently, the main sources of diffs come from timing information. Specifically:
1. The "Build successful (9761ms)" message in the `ember server` output
2. The QUnit test timing information in the screenshots
This commit introduce some new facilities to help scrub these incidental sources of indeterminism.
As part of this, we can also use said facilities to improve Windows compatibility.
It should also significantly improve deploy speed on master, since most of the time we won't have to spend 10+ minutes compressing PNGs that barely changed.

Deterministic builds

---

src/chapters/01-orientation.md

The last attempt didn't account for the little "progress" timestamps which are usually folded away _except_ when there is a failing test.
Unfortunately, to fix this, we'll have to churn all the screenshots again, but hopefully this time I really nailed it.

Deterministic builds (take 2)

---

src/chapters/01-orientation.md

We end up adding `cwd=super-rentals` to all the run commands after this but we never tell the user

Tell the user to go into the super-rentals dir

---

src/chapters/01-orientation.md

This is so that we don't have screenshot diffs due to shifts in line numbers.

Scrub stack traces in deterministic mode

---

src/chapters/01-orientation.md

`$'...'` is valid in bash, but not in sh (which is the default shell for running these commands).

Fix for sh

---

src/chapters/01-orientation.md

The upstream bug has been fixed in https://github.com/ember-cli/ember-cli/pull/8862 (ember-cli 3.13.1)

Fix `yarn start` in `ember new` output

---

src/lib/plugins/zoey-says/walker.ts

According to https://www.w3.org/WAI/tutorials/images/decorative/, decorative images should have `alt=""`.

Remove alt text for decorative image

---

src/chapters/06-interactive-components.md
src/lib/plugins/run-code-blocks/directives/screenshot.ts

I guess I was expecting `String.prototype.split` to work this way:
```js
> "click .rentals li:first-of-type article.rental .image".split(/\s+/, 2);
[ 'click', 'rentals li:first-of-type article.rental .image' ]
```
But it does not, it returns this:
```js
> "click .rentals li:first-of-type article.rental .image".split(/\s+/, 2);
[ 'click', '.rentals' ]
```
TL;DR I was expecting the limit parameter to mean that it will only split the first space, and the rest will be returned unspilt (like how it is in Ruby). However, it actually just split all the spaces anyway, the "extra" strings are just dropped from the returned array.

Fix bug in screenshot DSL parsing

---

src/lib/plugins/retina-images/walker.ts

The previous code didn't work correctly because it was trying to replace `<>"`, not (`<` or `>` or `"`).

Use regex correctly (－‸ლ)

---

.travis.yml
README.md

Without the token, the app won't build, so it's worth mentioning this in the README.

Add note about mapbox token to README

---

src/chapters/01-orientation.md

The `stack` property was turned into a getter in [this QUnit commit](https://github.com/qunitjs/qunit/commit/5742024ba0c298bc0782d76d97b81db4c48a81cf).
This broke the stacktrace scrubbing which caused [a screenshot diff](https://github.com/ember-learn/guides-source/pull/1135):
This commit fixed the issue by switching the assignment to use `Object.defineProperty` to overwrite QUnit's getter.

Fix stacktrace scrubbing

---

src/chapters/03-automated-testing.md
src/chapters/04-component-basics.md
src/chapters/05-more-about-components.md
src/chapters/06-interactive-components.md
src/chapters/07-reusable-components.md
src/chapters/08-working-with-data.md

It seems like we are slowing running up against the Travis build time limit, and with the part 2 work, we may have *just* crossed the line.
I think a lot of time is spent running `yarn test`, which has to first run a build (`ember build`) before it running the tests.
Since we already have the development server running in the and already rebuilding the app whenever we make changes, it may be faster if we just try to reuse the build in the tests.

Try speeding up the build

---

src/chapters/12-service-injection.md
src/lib/plugins/run-code-blocks/directives/screenshot.ts

Add a second parameter to the `click` screenshot DSL to denote "external" links that performs a navigation. This will wait for the navigation to complete before moving on to the next step and hopefully alleviate some of the build failures we are seeing with puppeteer reporting "Cannot take screenshot with 0 width".

Make screenshot less flaky

---

src/chapters/01-orientation.md

This is a one-line change. User feedback suggests that people were copy-pasting the `ember new` command as written in the prose, and then getting the wrong kind of app, so we should include the blueprint in that line. Thanks @runspired for relaying the info!

Clarify using the octane blueprint for ember new

---

src/markdown/tutorial/part-1/06-interactive-components.md

Deleted an extra "do" in the Zoey says in the responding to user interactions with actions section. Changed " forget to do add" to "forget to add".

[BUGFIX] remove accidental word in octane guide

---

.github/workflows/build.yml
README.md
package.json
src/markdown/tutorial/part-1/01-orientation.md
yarn.lock

Removes references to the Octane blueprint. Need to force re-runninng the tests after Ember-CLI v3.15 is out.

Merge this just after 3.15 Ember CLI release

---

src/markdown/tutorial/part-1/03-automated-testing.md
src/markdown/tutorial/part-1/04-component-basics.md
src/markdown/tutorial/part-1/05-more-about-components.md
src/markdown/tutorial/part-1/06-interactive-components.md
src/markdown/tutorial/part-1/07-reusable-components.md
src/markdown/tutorial/part-1/08-working-with-data.md
src/markdown/tutorial/part-2/09-route-params.md
src/markdown/tutorial/part-2/10-service-injection.md
src/markdown/tutorial/part-2/11-ember-data.md
src/markdown/tutorial/part-2/12-provider-components.md

This reduces the number of tests shown on screen and therefore the height of the screenshots (matching how it was when we were using the Octane blueprint).

Run tests with `nolint`

---

src/markdown/tutorial/part-1/08-working-with-data.md
src/markdown/tutorial/part-2/11-ember-data.md

- Typo in src/markdown/tutorial/part-2/11-ember-data.md
per https://github.com/ember-learn/guides-source/pull/1248#issuecomment-570293720
- Typo in src/markdown/tutorial/part-1/08-working-with-data.md
per https://github.com/ember-learn/guides-source/pull/1242#issuecomment-570299826

A number of copy fixes found in the release (Octane) guides

---

.github/workflows/build.yml

The `xargs` invocation in the image diffing step runs two tasks at the same time. When these two tasks try to access the git index concurrently, git will error, causing the function to think that the image is new (as it "didn't exist" on the current branch). This commit fixed the issue by first checking out the current branch to a temporary location before the parallel `xargs` is invoked.
Also reverts f6a95597fe48975e272de68fe3b67295edd21845 since it doesn't end up being necessary.

Fix race conditions with git

---

src/markdown/tutorial/part-1/01-orientation.md

This ensures the URLs can be navigated to directly.
Tested in https://github.com/ember-learn/super-rentals/pull/146

Add Netlify `_redirects` file

---

src/markdown/tutorial/part-2/10-service-injection.md

Twitter updated the intent API to use the "real" Twitter web app, which broke the selector. Further, it now requires logging in before seeing a meaningful page, so we probably just can't show the same screenshot anymore. Removing for now.

Remove Twitter screenshot

---

src/markdown/tutorial/part-1/06-interactive-components.md

Sometimes I'm not able to reproduce this issue in Ubuntu 20 on Firefox. 
What happens is that the tutorial places the Tomster image in `assets/images/` but the `Rental::Image` test passes in to `src` -> `asset/teaching-tomster.png`. It throws an error along the lines that it's not able to find the image.

fix: Rental::Image test uses correct asset location

---

src/markdown/tutorial/part-2/12-provider-components.md

[Guide](https://guides.emberjs.com/release/tutorial/part-2/provider-components/#toc_using-embers-input) is currently rendering this Input reference as an actual `<input>` element:

Add code markup to Input component reference

---

src/markdown/tutorial/part-1/03-automated-testing.md

In all the other assertions for the other pages, we also use the ´.jumbo´ class. While I understand this still works correctly for the tests in the tutorial, I feel like it is unnecessarily confusing for beginners (especially when it's not called out in the text after the example either).

Added missing .jumbo class for consistency's sake

---

src/markdown/tutorial/part-1/01-orientation.md
src/markdown/tutorial/part-1/02-building-pages.md
src/markdown/tutorial/part-1/03-automated-testing.md

For the pull request #165, I incorrectly asked the contributor to remove `*` around the placeholder links. The italics had been added for a reason, so I restored `*` where the placeholder links used to be.

Restored italics

---

.github/workflows/build.yml

Since November 16, the `set-env` command has been disabled in GitHub Actions for security reasons. I noticed the scheduled `build` workflow has been failing over the past few days.
Upgrading `webfactory/ssh-agent` action to the latest version, `v0.4.1`, should fix the issue.
- https://github.com/webfactory/ssh-agent/releases/tag/v0.4.1

Upgraded webfactory/ssh-agent action to v0.4.1

---

src/markdown/tutorial/part-1/08-working-with-data.md
src/markdown/tutorial/part-2/12-provider-components.md

This reverts commit cc75067669cf84ce881dd3f97496494b9a6b4c31.
Now that https://github.com/glimmerjs/glimmer-vm/pull/1255 has been merged and [upstream has been updated](https://github.com/emberjs/ember.js/pull/19363), https://github.com/emberjs/ember.js/issues/19360 is fixed and we can revert this workaround.
@chancancode

Revert "Fix beta build"

---

src/markdown/tutorial/part-2/10-service-injection.md

In [this section of the Service Injection page](https://guides.emberjs.com/release/tutorial/part-2/service-injection/#toc_why-we-cant-test-windowlocationhref), the code snippet for the `super-rentals-test.js` file lacks syntax highlighting because the snippet language was set to Handlebars when it should be JavaScript:

Fix JS snippet syntax highlighting

---

src/markdown/tutorial/part-1/01-orientation.md

Closes https://github.com/ember-learn/super-rentals-tutorial/issues/173.

add --lang option to tutorial fixes issue #173

---

.github/workflows/build.yml
CONTRIBUTING.md
README.md

In `super-rentals-tutorial` and `super-rentals`, I used GitHub's `Rename default branch` feature to rename the default branch to `main`. This feature automatically updates the destination branch for any open pull requests.
On Heroku and Netlify, I updated the branch to `main` (for `super-rentals`) as well:

Updated default branch name

---

src/assets/downloads/data/api/rentals.json
src/assets/downloads/data/api/rentals/urban-living.json
src/markdown/tutorial/part-2/12-provider-components.md

The previous image is no longer available on wiki commons. This new image of a building in Seattle. More info about it is here: https://commons.wikimedia.org/wiki/File:Seattle_-_Barnes_and_Bell_Buildings.jpg
The broken image blocks the app building steps that publish to the Ember Guides and to the example app.

Replace broken image, closes #182

---

src/markdown/tutorial/part-1/01-orientation.md

The tutorial text states that the `--lang en` option will be passed but the generated example doesn't show that.
I am not able to test the execution of this change, but as it's effectively a typo change I hope you will be able to make use of the request.

Update the display text to match expectations

---

.github/workflows/build.yml
src/markdown/tutorial/part-1/03-automated-testing.md
src/markdown/tutorial/part-1/04-component-basics.md
src/markdown/tutorial/part-2/09-route-params.md
src/markdown/tutorial/part-2/10-service-injection.md
src/markdown/tutorial/part-2/11-ember-data.md

See https://github.com/ember-cli/ember-cli/pull/9667

Update tutorial to use `assert.strictEqual` in place of `assert.equal` to pass eslint-plugin-qunit

---

.github/workflows/build.yml

Restores running CI for release. Should only be merged once this PR is green after the release of Ember 4.0

Restore CI for release -- should only merge after Ember v4 is released

---

.github/workflows/build.yml

Should pass once https://github.com/ember-cli/ember-cli/pull/9739 is released in a CLI beta release

Re-enable beta tutorial build

---

src/markdown/tutorial/part-1/01-orientation.md

QUnit's reporter was refactored to use the new `runEnd` event[1]. This broke the previous hack as modifying the `details` object in the `done` hook no longer does anything.
[1]: https://github.com/qunitjs/qunit/pull/1643

Fix the "deterministic tests" hack

---

.local.dic
README.md
src/markdown/tutorial/part-2/11-ember-data.md
src/markdown/tutorial/part-2/index.md
src/markdown/tutorial/part-2/recap.md

This is now the standard naming and branding for the library. Let's get this set across the board where we can.
Sister PR for the Guides - https://github.com/ember-learn/guides-source/pull/1896

Find/replace Ember Data for EmberData

---

src/markdown/tutorial/part-2/11-ember-data.md

[Here](https://guides.emberjs.com/release/tutorial/part-2/ember-data/#toc_emberdata-models), close parenthesis is missing.
Ref: https://github.com/ember-learn/guides-source/pull/2024#issuecomment-2045200068

Add missed closing parenthesis

---

src/markdown/tutorial/part-1/04-component-basics.md
src/markdown/tutorial/part-1/05-more-about-components.md
src/markdown/tutorial/part-2/09-route-params.md

Noticed some code fence blocks were handlebars, but the language for highlighting was configured to `js`.

fix: use handlebars as code fence lang

---

.github/workflows/build.yml

Myself and @jaredgalanis did some investigation on this and found that some of the noise that is happening because of slight differences in the maps would be under the threshold of 1000 pixels different. This might be tweaked later but I think we should try this for a little while

add a threshold to perceptualdiff to prevent so much image churn

---

CONTRIBUTING.md
package.json
src/assets/downloads/style.css
src/markdown/tutorial/part-1/01-orientation.md
src/markdown/tutorial/part-2/11-ember-data.md
yarn.lock

~Prettier is failing on `app/templates/index.hbs` because it has a newline at the end of the file. It is odd, because afaict prettier enforces newlines at the end of the file.~
~So far, I have tried editing the `.editorconfig` to change `insert_final_newline = false` under hbs to true. This had no effect (as expected because we are not using and editor to modify the files and because prettier does not respect this configuration).~
~I also tried the route of running `yarn format` after creating the `index.hbs` file. This is a problem because all future patches bring back the newline and also because all future diffs would need to be edited.~
~Update:
It appears that prettier does strip newlines in handlebars https://github.com/prettier/prettier/pull/10759 so the question is why did it not …

Attempt to fix build

---

.github/workflows/build.yml
.local.dic
README.md
pnpm-lock.yaml
src/markdown/tutorial/part-1/07-reusable-components.md

This PR builds on TeriyakiBomb's PR branch and fixes up all the code and non-code parts of Chapter 7 to get it working with TomTom.  (I couldn't push to that fork.)
This addresses all of the comments I left on the original PR.  It was mostly just a matter of fixing up the URL & params to use TomTom's API instead of the Mapbox API, then regenerating the component and test patches to reflect these changes.
**IMPORTANT:** To get CI working, somebody needs to put a TomTom key in the workflow build.yml file.  The [Mapbox key is hardcoded](https://github.com/ember-learn/super-rentals-tutorial/blob/main/.github/workflows/build.yml#L82) in the build.yml file, so it should just be a matter of replacing that with a TomTom key.

Replace map box with TomTom
