ember-learn/super-rentals-tutorial

.travis.yml, README.md, package.json, src/chapters/01-orientation.md, src/lib/plugins/run-code-blocks/directives/checkpoint.ts, src/lib/plugins/run-code-blocks/directives/command.ts, src/lib/plugins/run-code-blocks/directives/file/copy.ts, src/lib/plugins/run-code-blocks/directives/file/create.ts, src/lib/plugins/run-code-blocks/directives/file/patch.ts, yarn.lock
Instead, add it as a dev dependency and have CI ensure we test with the latest version.
=> Don't install `ember-cli` globally

src/chapters/05-creating-components.md
Integrates all chapters related to creating components into one.
=> Add chapter 5

src/chapters/03-automated-testing.md
The linting rules in the guides repo disallows this
=> really really -> really, really

.travis.yml
It only helps a little bit, but better than nothing
=> Parallelize PNG optimizations

README.md, src/chapters/01-orientation.md, src/chapters/04-component-basics.md, src/chapters/05-more-about-components.md, src/chapters/06-interactive-components.md, src/lib/plugins/run-code-blocks/directives/checkpoint.ts, src/lib/plugins/run-code-blocks/directives/file/patch.ts, src/lib/plugins/run-code-blocks/servers.ts
@jenweber I picked out the first bits from #26 and fixed the errors. I also reverted the headers for now (though we should definitely add them back later), as I want to finish splitting up the chapters first, and then go back to do an editorial pass on all the chapters at once.
=> More content!

.travis.yml
See https://github.com/travis-ci/docs-travis-ci-com/pull/2513
=> Try moving to xenial

src/chapters/00-part-1.md, src/chapters/01-orientation.md, src/chapters/05-more-about-components.md, src/chapters/06-interactive-components.md, src/chapters/07-reusable-components.md, src/chapters/08-working-with-data.md
Part of ember-learn/guides-source#1070
=> Add more prose, fill in the WIPs

src/chapters/01-orientation.md, src/chapters/03-automated-testing.md, src/chapters/04-component-basics.md, src/chapters/05-more-about-components.md, src/chapters/06-interactive-components.md, src/chapters/07-reusable-components.md
These were spotted and suggested by @ijlee2 on ember-learn/guides-source#1070
=> Fix various content bugs

src/bin/generate.ts
Both passes processed from the same `inputPath` -> `outputPath`, so the work we did on the first pass was completely wiped out by the post-processing pass. Oops.
=> Oops I made a huge mistake 🧨

src/chapters/01-orientation.md
A `yarn.lock` leaked into the `tree` output!
=> Try harder to fake NPM

src/chapters/08-working-with-data.md
This sentence didn't read well for me. My changes don't make it perfect, but I think it's an improvement.
=> Improve sentence explaining model hook

src/chapters/01-orientation.md
=> Enable checkpoint at chapter 1

src/chapters/08-working-with-data.md
=> Fixed minor typos in Working With Data

src/chapters/00-part-1.md, src/chapters/01-orientation.md, src/chapters/02-building-pages.md, src/chapters/03-automated-testing.md, src/chapters/04-component-basics.md, src/chapters/05-more-about-components.md, src/chapters/06-interactive-components.md, src/chapters/07-reusable-components.md, src/chapters/08-working-with-data.md, src/chapters/09-part-1-recap.md
1. Added chapter intro summaries and section headers
2. Did a general editorial pass, including rewording things for clarity as well as fixing typos
=> Copy edit pass

README.md, src/chapters/11-route-params.md, src/chapters/12-service-injection.md, src/chapters/13-ember-data.md
1. Added chapter intro summaries and section headers
2. Did a general editorial pass, including rewording things for clarity
as well as fixing typos
=> Copy edit pass: part 2

src/chapters/01-orientation.md
Current Text: If you are already familiar with them, you should feel right at home here.
Updated Text: If you are already familiar with HTML, you should feel right at home here.
=> Update them to HTML for clarity

src/chapters/02-building-pages.md
Interoperability is a pretty specialized word from computer science which might be intimidating for some folks.
=> Use simpler language for screen reader interoperability

src/chapters/08-working-with-data.md
https://github.com/ember-learn/guides-source/pull/1148#issuecomment-546466827
=> Update Octane tutorial

scripts/optimize-screenshot.sh
This reverts commit 783c3ee0acedd02725761c6a85fcf7e44aeb6690.
=> Revert "Temporarily disable image optimization"

src/chapters/11-route-params.md, src/chapters/14-provider-components.md
Addresses suggested comments in https://github.com/ember-learn/guides-source/pull/1159.
=> Tweak prose + fix typos as per @jenweber's suggestions.

src/chapters/01-orientation.md, src/chapters/02-building-pages.md, src/chapters/04-component-basics.md, src/chapters/05-more-about-components.md, src/chapters/06-interactive-components.md, src/chapters/07-reusable-components.md, src/chapters/08-working-with-data.md, src/chapters/11-route-params.md, src/chapters/12-service-injection.md, src/chapters/13-ember-data.md, src/chapters/14-provider-components.md
Attempt to make screenshots a little more deterministic
=> Improve screenshots

.github/workflows/build.yml
See https://github.com/ember-learn/guides-source/pull/1166
=> Don't push empty commits

.github/workflows/build.yml, src/markdown/tutorial/part-1/01-orientation.md, src/markdown/tutorial/part-1/08-working-with-data.md, src/markdown/tutorial/part-2/09-route-params.md, src/markdown/tutorial/part-2/10-service-injection.md, src/markdown/tutorial/part-2/11-ember-data.md, src/markdown/tutorial/part-2/12-provider-components.md
Fix some minor issues that showed up on https://github.com/ember-learn/guides-source/pull/1199
=> Reorg (take 2)

src/markdown/tutorial/part-2/09-route-params.md, src/markdown/tutorial/part-2/10-service-injection.md
The values should be separated by space instead of comma.
=> Fix `rel` attributes

src/markdown/tutorial/acceptance-test.md, src/markdown/tutorial/autocomplete-component.md, src/markdown/tutorial/deploying.md, src/markdown/tutorial/ember-cli.md, src/markdown/tutorial/ember-data.md, src/markdown/tutorial/hbs-helper.md, src/markdown/tutorial/installing-addons.md, src/markdown/tutorial/model-hook.md, src/markdown/tutorial/routes-and-templates.md, src/markdown/tutorial/service.md, src/markdown/tutorial/simple-component.md, src/markdown/tutorial/subroutes.md
Related to work in https://github.com/ember-learn/guides-source/pull/1210
=> add redirects for old tutorial files

src/markdown/tutorial/part-1/01-orientation.md
Remove testem patch: https://github.com/ember-cli/ember-cli/pull/8986
=> Updates for ember-cli 3.16

src/markdown/tutorial/part-1/01-orientation.md, src/markdown/tutorial/part-2/11-ember-data.md
=> Raise on deprecation, fix Ember Data default serializer deprecation

.github/workflows/build.yml, src/markdown/tutorial/part-1/index.md
Push directly to the master branch of https://github.com/ember-learn/super-rentals
=> Fix deploy

src/markdown/tutorial/part-2/12-provider-components.md
=> Fix pluralization

src/markdown/tutorial/part-2/10-service-injection.md
@chancancode can you look this over. This pull request is for issue "Update tutorial text #148"
=> Took-out-tutorial-text-referring-to-internet-deploy 

.local.dic, package.json, src/markdown/tutorial/part-1/01-orientation.md, yarn.lock
It should go into `EmberENV`, not `APP`.
=> Set `RAISE_ON_DEPRECATION` properly

README.md, src/lib/plugins/run-code-blocks/directives/checkpoint.ts, src/lib/plugins/run-code-blocks/server.ts, src/markdown/tutorial/part-1/01-orientation.md, src/markdown/tutorial/part-1/07-reusable-components.md
This is probably the closest thing to the "negative PID" thing in POSIX to kill a process group.
=> Use "tree kill" on windows to stop servers

src/markdown/tutorial/part-1/04-component-basics.md, src/markdown/tutorial/part-1/06-interactive-components.md
Let me know if there's anything I need to adjust on this PR
=> add missing semicolons

src/markdown/tutorial/part-1/01-orientation.md, src/markdown/tutorial/part-1/02-building-pages.md, src/markdown/tutorial/part-1/03-automated-testing.md
The issue: https://github.com/ember-learn/super-rentals-tutorial/issues/160
=> Add links for learning more (part 1 of 4)

src/markdown/tutorial/part-1/07-reusable-components.md, src/markdown/tutorial/part-1/08-working-with-data.md, src/markdown/tutorial/part-2/09-route-params.md
This pull request closes #162.
=> Added all requested links and changes.

src/markdown/tutorial/part-1/04-component-basics.md, src/markdown/tutorial/part-1/05-more-about-components.md, src/markdown/tutorial/part-1/06-interactive-components.md
This pull request closes #161.
=> Add links for learning more (part 2 of 4)

src/markdown/tutorial/part-1/01-orientation.md, src/markdown/tutorial/part-1/02-building-pages.md, src/markdown/tutorial/part-1/03-automated-testing.md, src/markdown/tutorial/part-1/04-component-basics.md, src/markdown/tutorial/part-1/05-more-about-components.md, src/markdown/tutorial/part-1/06-interactive-components.md, src/markdown/tutorial/part-1/07-reusable-components.md, src/markdown/tutorial/part-1/08-working-with-data.md, src/markdown/tutorial/part-2/09-route-params.md, src/markdown/tutorial/part-2/10-service-injection.md, src/markdown/tutorial/part-2/11-ember-data.md, src/markdown/tutorial/part-2/12-provider-components.md
=> updated "ember server" references to "ember serve"

.github/workflows/build.yml
I have added the secret to the repo.
=> Notify in Discord when nightly runs of tutorial build fail

src/assets/downloads/style.css
Ignoring the nesting specificity rule -- it would take some work to figure it out and maintain the styles.
=> Fix Beta build: Update stylesheet with fixes from stylelint

src/markdown/tutorial/part-1/01-orientation.md
=> Update patch to match updated blueprint for app/templates/application.hbs

README.md, src/markdown/tutorial/part-1/01-orientation.md, src/markdown/tutorial/part-1/02-building-pages.md, src/markdown/tutorial/part-1/03-automated-testing.md, src/markdown/tutorial/part-1/04-component-basics.md, src/markdown/tutorial/part-1/05-more-about-components.md, src/markdown/tutorial/part-1/06-interactive-components.md, src/markdown/tutorial/part-1/07-reusable-components.md, src/markdown/tutorial/part-1/08-working-with-data.md, src/markdown/tutorial/part-2/09-route-params.md, src/markdown/tutorial/part-2/10-service-injection.md, src/markdown/tutorial/part-2/11-ember-data.md, src/markdown/tutorial/part-2/12-provider-components.md
Per RFC #831 https://rfcs.emberjs.com/id/0831-standardize-use-npm-yarn
=> Switch ember serve(r) -> npm start

src/markdown/tutorial/part-2/11-ember-data.md
current blueprint uses const https://github.com/emberjs/data/blob/main/packages/model/blueprints/model-test/qunit-files/__root__/__path__/__test__.js
=> fix: use const to match generated output

src/markdown/tutorial/part-2/11-ember-data.md
=> Fix service/store.js filename 

src/markdown/tutorial/part-1/04-component-basics.md
Made a typo here https://github.com/ember-learn/super-rentals-tutorial/pull/241/files
=> fix: typo in code fence blocks

src/markdown/tutorial/part-1/01-orientation.md, src/markdown/tutorial/part-1/06-interactive-components.md, src/markdown/tutorial/part-1/07-reusable-components.md, src/markdown/tutorial/part-2/10-service-injection.md, src/markdown/tutorial/part-2/12-provider-components.md
This will fail on release until release is 5.11
=> Updates to the tutorial so it works on 5.11

src/assets/downloads/style.css, src/markdown/tutorial/part-2/12-provider-components.md
=> Switch to using a <form> element and FormData rather than <Input>

package.json, yarn.lock
this allows you to run things locally without it exploding 🙈
=> update ember-cli in the yarn.lock

.github/workflows/build.yml
https://github.com/puppeteer/puppeteer/issues/12818
=> Pin Ubuntu due to chromium bug (via puppeteer)

src/markdown/tutorial/part-1/01-orientation.md, src/markdown/tutorial/part-1/02-building-pages.md, src/markdown/tutorial/part-1/03-automated-testing.md, src/markdown/tutorial/part-1/04-component-basics.md, src/markdown/tutorial/part-1/05-more-about-components.md, src/markdown/tutorial/part-1/06-interactive-components.md, src/markdown/tutorial/part-1/07-reusable-components.md, src/markdown/tutorial/part-1/08-working-with-data.md, src/markdown/tutorial/part-2/09-route-params.md, src/markdown/tutorial/part-2/10-service-injection.md, src/markdown/tutorial/part-2/12-provider-components.md
Reverts ember-learn/super-rentals-tutorial#268
Yes this is a revert of a revert 🙈 we should never have reverted, we should have left the tutorial as is and done some git-fu on the guides-source side 👍
=> Revert "Revert "Strict mode""
